spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jwt?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      show_sql: true
    generate-ddl: true
    open-in-view: false

server:
  error:
    include-stacktrace: never

# JWT
jwt:
  secret:
    key: MgNkXjMsd4DyflPfNEYsVGQXiVI3l0qR
  time:
    expiration: 86400000
