spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jwt?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
